import { VertexAI } from '@google-cloud/vertexai';
import { retryWithBackoff } from '../utils/asyncPool.js';

// Initialize Vertex AI
let vertexAI = null;

function getVertexAI() {
  if (!vertexAI) {
    const projectId = process.env.GOOGLE_PROJECT_ID;
    if (!projectId) {
      throw new Error('GOOGLE_PROJECT_ID environment variable is not set');
    }

    vertexAI = new VertexAI({
      project: projectId,
      location: 'us-central1'
    });
  }
  return vertexAI;
}

/**
 * Generate image from text prompt using Google Imagen
 * @param {string} prompt - Text description of image to generate
 * @param {string} aspectRatio - Aspect ratio (default: '16:9')
 * @returns {Promise<Buffer>} - Image buffer
 */
export async function generateImage(prompt, aspectRatio = '16:9') {
  return retryWithBackoff(async () => {
    const vertex = getVertexAI();

    const model = vertex.preview.getGenerativeModel({
      model: 'imagegeneration@006'
    });

    const request = {
      prompt: prompt,
      numberOfImages: 1,
      aspectRatio: aspectRatio,
      safetyFilterLevel: 'block_some',
      personGeneration: 'allow_adult'
    };

    try {
      const result = await model.generateImages(request);

      if (!result.images || result.images.length === 0) {
        throw new Error('No images generated by Google Imagen');
      }

      const image = result.images[0];

      // Convert base64 to buffer if needed
      if (image.bytesBase64Encoded) {
        return Buffer.from(image.bytesBase64Encoded, 'base64');
      }

      // If URL is provided, fetch the image
      if (image.url) {
        const response = await fetch(image.url);
        if (!response.ok) {
          throw new Error(`Failed to fetch image: ${response.statusText}`);
        }
        const arrayBuffer = await response.arrayBuffer();
        return Buffer.from(arrayBuffer);
      }

      throw new Error('No image data returned from Google Imagen');
    } catch (error) {
      // Parse Google API errors
      if (error.message?.includes('safety')) {
        throw new Error('Content policy violation: Image generation blocked by safety filters');
      }
      if (error.message?.includes('quota')) {
        throw new Error('Google Imagen API quota exceeded. Please try again later.');
      }
      if (error.message?.includes('permission') || error.message?.includes('auth')) {
        throw new Error('Google Imagen API authentication failed. Check your credentials.');
      }
      throw error;
    }
  }, 3, 1000);
}

/**
 * Generate image from source image + modification prompt (image-to-image)
 * @param {Buffer} sourceImageBuffer - Source image buffer
 * @param {string} prompt - Modification prompt
 * @param {string} aspectRatio - Aspect ratio (default: '16:9')
 * @returns {Promise<Buffer>} - Modified image buffer
 */
export async function tweakImage(sourceImageBuffer, prompt, aspectRatio = '16:9') {
  return retryWithBackoff(async () => {
    const vertex = getVertexAI();

    const model = vertex.preview.getGenerativeModel({
      model: 'imagegeneration@006'
    });

    const base64Image = sourceImageBuffer.toString('base64');

    const request = {
      prompt: prompt,
      numberOfImages: 1,
      aspectRatio: aspectRatio,
      referenceImage: {
        bytesBase64Encoded: base64Image
      },
      editMode: 'product-image', // or 'inpainting-insert', 'inpainting-remove'
      safetyFilterLevel: 'block_some'
    };

    try {
      const result = await model.generateImages(request);

      if (!result.images || result.images.length === 0) {
        throw new Error('No images generated by Google Imagen');
      }

      const image = result.images[0];

      if (image.bytesBase64Encoded) {
        return Buffer.from(image.bytesBase64Encoded, 'base64');
      }

      if (image.url) {
        const response = await fetch(image.url);
        if (!response.ok) {
          throw new Error(`Failed to fetch image: ${response.statusText}`);
        }
        const arrayBuffer = await response.arrayBuffer();
        return Buffer.from(arrayBuffer);
      }

      throw new Error('No image data returned from Google Imagen');
    } catch (error) {
      if (error.message?.includes('safety')) {
        throw new Error('Content policy violation: Image modification blocked by safety filters');
      }
      if (error.message?.includes('quota')) {
        throw new Error('Google Imagen API quota exceeded. Please try again later.');
      }
      throw error;
    }
  }, 3, 1000);
}

/**
 * Test if Google Imagen is properly configured
 * @returns {Promise<{valid: boolean, message: string}>}
 */
export async function testGoogleImagen() {
  try {
    const vertex = getVertexAI();

    // Try to initialize the model (doesn't make API call)
    const model = vertex.preview.getGenerativeModel({
      model: 'imagegeneration@006'
    });

    return {
      valid: true,
      message: 'Google Imagen configuration is valid'
    };
  } catch (error) {
    return {
      valid: false,
      message: error.message || 'Google Imagen configuration failed'
    };
  }
}

export default {
  generateImage,
  tweakImage,
  testGoogleImagen
};
